language: java
addons:
  apt:
    packages:
    - xmlstarlet
    - graphviz
jdk:
- oraclejdk11
after_success:
- wget -O settings.xml https://raw.githubusercontent.com/pousse-cafe/pousse-cafe-deploy/master/snapshot_release_settings.xml
- ./can_auto_deploy.sh && mvn deploy --settings settings.xml
env:
  global:
  - secure: D6IoOh9+67fJRuJXx7kzCix6T8nrC6xYzevqIq39buIsYrNjjo37Vnv6Bzfw4zE4NnicBjyvY+kVURbfjbJ9SmCI/d2LPEtCR2C3dNsZnEi/Tilc2tGOLpQs0XzjOJyL7Yo3HAwVWdNUx7ZA/R8mod+sk69BlMexphFFu+NqYLOXa/OJSUtg1ThurSzJ+9lD5xCCgaNCVUTTdBRLU0Wvo5eAAe2PCWwCT4S0wOId9xONjPXEE884QFw3gOJkIBouRnc1XjeJqjoZqBk9On7ek7xXW2UHjZHxsPQLrreEKxp6lrlzRSqsMkViq8oTD4YTCTipB952dXSU5gHWh8z4IcY87uwj63PHDhdkB2Sxw7FrVFGslxyW/AmuwupEJyfLdTEECvNj2qEWflQL6z0Dh7HKtVu4VEkic/cOEupU8aDQhZbDrHcnJgd/zV1O4V4WVrKWJeJt1AkVQ+/QWfMntDI8NNfGFP9WW6wtNHTPdtt61LgUKYhjAu9DXTZUC4iv+gMyTjWCrniDIIRKG2QnE71uME9kVs6q0CiMxR+0vwpdYzCuUggqCJ6T12L4hD0H7g8+uPAdVtoCJBWlvbFXPWey9iB/QAMAF4fQOJnLyZ4lbzRqhhPTL3HnB74+NPa7ASV7VMNQ9XyT15lE174JRuJiib9pYMJzPIR5XxTRKQ0=
  - secure: hLMWEZzSZ9lI74bDPNgC8QGoRW/dERO1semxKSr9+of8kUUj6cLQySXaeeyhLEu8OS4ZRMtJOJu0F23gFUbMvsVwhE60kS3Q0AXm4dKQ6X7lD8GRJ+tsxfqzZo0HQa+382Vw/XikXYXCgUeIU2qvOvCmmvBkNU9aA5pgzIq+lm9hYNBTk9KWjzJeHTMJ6zHQv1kDscZGRChIFr8pNtOZ0NLH0ym9e6kGtFtAoB40jyGConc4G1/8zCgqyt9Tpr68g1cpf7mkd2cgn+wEhFFC9FQ0WLJLe6k5va1U+DDWnmD/BQgIr28IdFA1Vmw76HCPIHmtTj4i48ib2Ht/lWetsTecwnOUkT9SqRzWsOh9IVdDzzvA8xdy05pZkyX6bGgTA6M3NY+zDJKfBd7GuTaCkTm6r1wO38V7wMbIu0ZJk89GlnN3cMDkUemEk+kdahoVHAD01LC3tMdHxnwnXHWnoPn6V36Cv1VfnLP2tmrgwfsbzp63J/v1us1n40lx8Ug3mPXICZ+T1t5KeNLIjYfOaSDPfn7Hm0eIv/jn8F8qEerksNmwObDOWYT6kdzhFIYlGnloiknkyhGcdLFsW704MeX4NmAF2By8jOVpRdu83vKnlCxdqaOE4d02gsMEPQOIlb8wGru92HRqzg+XYsRZJdCTq5qtS/BLd+67Iw9n2pE=
